[2022-04-19 09:33:58,683] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.log_start manual__2022-04-19T09:32:54.579466+00:00 [queued]>
[2022-04-19 09:33:58,690] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.log_start manual__2022-04-19T09:32:54.579466+00:00 [queued]>
[2022-04-19 09:33:58,691] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 09:33:58,691] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-04-19 09:33:58,691] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 09:33:58,698] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): log_start> on 2022-04-19 09:32:54.579466+00:00
[2022-04-19 09:33:58,701] {standard_task_runner.py:52} INFO - Started process 2082 to run task
[2022-04-19 09:33:58,704] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'hook_dag', 'log_start', 'manual__2022-04-19T09:32:54.579466+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/hook_dag.py', '--cfg-path', '/tmp/tmpko5kpqd_', '--error-file', '/tmp/tmpoo9x9vac']
[2022-04-19 09:33:58,705] {standard_task_runner.py:77} INFO - Job 171: Subtask log_start
[2022-04-19 09:33:58,752] {logging_mixin.py:109} INFO - Running <TaskInstance: hook_dag.log_start manual__2022-04-19T09:32:54.579466+00:00 [running]> on host 22e04adb6bfa
[2022-04-19 09:33:58,789] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hook_dag
AIRFLOW_CTX_TASK_ID=log_start
AIRFLOW_CTX_EXECUTION_DATE=2022-04-19T09:32:54.579466+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-19T09:32:54.579466+00:00
[2022-04-19 09:33:58,795] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-19 09:33:58,798] {dbapi.py:225} INFO - Running statement: do $$
declare
	q_stream integer;
begin  
	select 1 into q_stream
	from list_flow_log
	where object_flow = 1 and status = 1;
  
	if q_stream > 0 then
		raise exception 'IP-offline - The stream is blocked';
	else 
  		INSERT INTO list_flow_log (object_flow, t_start, status) VALUES(1, NOW(), 1);
	end if;

end $$, parameters: None
[2022-04-19 09:33:58,799] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "object_flow" does not exist
LINE 2:  where object_flow = 1 and status = 1
               ^
QUERY:  select 1                from list_flow_log
	where object_flow = 1 and status = 1
CONTEXT:  PL/pgSQL function inline_code_block line 5 at SQL statement

[2022-04-19 09:33:58,808] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=hook_dag, task_id=log_start, execution_date=20220419T093254, start_date=20220419T093358, end_date=20220419T093358
[2022-04-19 09:33:58,816] {standard_task_runner.py:92} ERROR - Failed to execute job 171 for task log_start
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "object_flow" does not exist
LINE 2:  where object_flow = 1 and status = 1
               ^
QUERY:  select 1                from list_flow_log
	where object_flow = 1 and status = 1
CONTEXT:  PL/pgSQL function inline_code_block line 5 at SQL statement

[2022-04-19 09:33:58,839] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-19 09:33:58,933] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
