[2022-04-27 09:23:10,907] {taskinstance.py:1031} INFO - Dependencies not met for <TaskInstance: cso_2295_ipo_2_cso_xls.py.log_sensor3 scheduled__2022-04-25T15:41:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-04-27 09:23:10,909] {local_task_job.py:99} INFO - Task is not able to be run
