[2022-04-07 08:25:24,383] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_project.inaccurate scheduled__2022-04-06T00:00:00+00:00 [queued]>
[2022-04-07 08:25:24,409] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_project.inaccurate scheduled__2022-04-06T00:00:00+00:00 [queued]>
[2022-04-07 08:25:24,409] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 08:25:24,409] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-07 08:25:24,409] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 08:25:24,443] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): inaccurate> on 2022-04-06 00:00:00+00:00
[2022-04-07 08:25:24,447] {standard_task_runner.py:52} INFO - Started process 89 to run task
[2022-04-07 08:25:24,449] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_project', 'inaccurate', 'scheduled__2022-04-06T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/my_project.py', '--cfg-path', '/tmp/tmpo53n2xlo', '--error-file', '/tmp/tmpm3sh0idc']
[2022-04-07 08:25:24,450] {standard_task_runner.py:77} INFO - Job 52: Subtask inaccurate
[2022-04-07 08:25:24,569] {logging_mixin.py:109} INFO - Running <TaskInstance: my_project.inaccurate scheduled__2022-04-06T00:00:00+00:00 [running]> on host abd567e83fcb
[2022-04-07 08:25:24,709] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_project
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-06T00:00:00+00:00
[2022-04-07 08:25:24,710] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-07 08:25:24,711] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-04-07 08:25:24,722] {subprocess.py:85} INFO - Output:
[2022-04-07 08:25:24,723] {subprocess.py:89} INFO - inaccurate
[2022-04-07 08:25:24,724] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-07 08:25:24,790] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=my_project, task_id=inaccurate, execution_date=20220406T000000, start_date=20220407T082524, end_date=20220407T082524
[2022-04-07 08:25:24,835] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 08:25:24,901] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
