[2022-04-07 13:51:49,364] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table manual__2022-04-07T13:51:47.127693+00:00 [queued]>
[2022-04-07 13:51:49,372] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table manual__2022-04-07T13:51:47.127693+00:00 [queued]>
[2022-04-07 13:51:49,372] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 13:51:49,372] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-07 13:51:49,372] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 13:51:49,381] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): populate_pet_table> on 2022-04-07 13:51:47.127693+00:00
[2022-04-07 13:51:49,385] {standard_task_runner.py:52} INFO - Started process 1802 to run task
[2022-04-07 13:51:49,388] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'populate_pet_table', 'manual__2022-04-07T13:51:47.127693+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmpy0o1_ts_', '--error-file', '/tmp/tmpqw5rtcok']
[2022-04-07 13:51:49,389] {standard_task_runner.py:77} INFO - Job 88: Subtask populate_pet_table
[2022-04-07 13:51:49,432] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.populate_pet_table manual__2022-04-07T13:51:47.127693+00:00 [running]> on host d73239f69a26
[2022-04-07 13:51:49,495] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=populate_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2022-04-07T13:51:47.127693+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-07T13:51:47.127693+00:00
[2022-04-07 13:51:49,504] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-07 13:51:49,508] {dbapi.py:225} INFO - Running statement: 
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Max', 'Dog', '2018-07-05', 'Jane');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Susie', 'Cat', '2019-05-01', 'Phil');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Lester', 'Hamster', '2020-06-23', 'Lily');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Quincy', 'Parrot', '2013-08-11', 'Anne');
            , parameters: None
[2022-04-07 13:51:49,509] {dbapi.py:233} INFO - Rows affected: 1
[2022-04-07 13:51:49,521] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=populate_pet_table, execution_date=20220407T135147, start_date=20220407T135149, end_date=20220407T135149
[2022-04-07 13:51:49,560] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 13:51:49,618] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
